DROP TABLE IF EXISTS catser_items CASCADE;
DROP TABLE IF EXISTS catser_classes CASCADE;
DROP TABLE IF EXISTS catser_groups CASCADE;
DROP TABLE IF EXISTS catser_divisions CASCADE;
DROP TABLE IF EXISTS catser_sections CASCADE;
